#!/bin/bash

# Instructions: To make sure you can run this file type "ls -l" in the command prompt. This will indicate whether you can run the file.
# The next step is to type "sudo chmod u+x {this file path}"

# update apt-get
sudo apt-get update

# install programs
sudo apt-get install python3
# sudo apt-get install git

# Python 3 Packages Here
#python3 -m pip install pandas
#python3 -m pip install matplotlib.pyplot
#python3 -m pip install numpy
